### ISSUE TITLE
Issue in production

### ISSUE THREAD

**Issue by talmax1124** [colbyfayock/uix-cloudinary-input#1]
<img width="1512" alt="Screen Shot 2022-02-09 at 10 16 44 AM" src="https://user-images.githubusercontent.com/61528430/153230849-e27a9bbd-4633-4b17-9b69-9f65e8b1b743.png">

**Comment by colbyfayock** [comment]
hey this is meant to be used for GraphCMS and really is just me testing it out right now :)
